name: flutter_todos
description: An example todos app that showcases bloc state management patterns.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  intl: ^0.19.0
  formz: ^0.6.0
  google_fonts: ^6.2.1
  meta: ^1.15.0
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.4.1
  flow_builder: ^0.1.0
  google_sign_in: ^6.2.1


  firestore_todos_api:
    path: packages/firestore_todos_api
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.1
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.7
  mockingjay: ^0.6.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
