name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  meta: ^1.15.0

dev_dependencies:
  firebase_auth_platform_interface: ^7.4.4
  firebase_core_platform_interface: ^5.2.1
  plugin_platform_interface: ^2.1.8
