// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPZZdL39SyAsWSUEzPKX8LnSoMEGrO-a0',
    appId: '1:123700400153:web:76c21034bcc138bf121a88',
    messagingSenderId: '123700400153',
    projectId: 'login-sign-up-user',
    authDomain: 'login-sign-up-user.firebaseapp.com',
    databaseURL: 'https://login-sign-up-user-default-rtdb.firebaseio.com',
    storageBucket: 'login-sign-up-user.appspot.com',
    measurementId: 'G-D04FH06311',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD__CsEJkKbFn61wh__I1H6kOXq6uOqjg8',
    appId: '1:123700400153:android:e19ff7fb69917c77121a88',
    messagingSenderId: '123700400153',
    projectId: 'login-sign-up-user',
    databaseURL: 'https://login-sign-up-user-default-rtdb.firebaseio.com',
    storageBucket: 'login-sign-up-user.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWnfrJ81375Gui5h5NARIwzB2dCIrp_V4',
    appId: '1:123700400153:ios:f65cf904a8921e59121a88',
    messagingSenderId: '123700400153',
    projectId: 'login-sign-up-user',
    databaseURL: 'https://login-sign-up-user-default-rtdb.firebaseio.com',
    storageBucket: 'login-sign-up-user.appspot.com',
    iosClientId: '123700400153-egsf14rdc8qvhpvoa30h2d88uvcmlkgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.flutter-todos',
  );
}
